# All values in no of frames
BACKGROUND_COLOR: '#000000'
FRAME_RATE: 60

STIM_COLOR: '#ffffff'
STIM_EMPTY_MS: 1000
REACTION_KEYS: ['f', 'g', 'h', 'j']

QUE_RADIUS: 10
QUE_TIME_MS: 200
QUE_CORRECT_COLOR: '#00FF00'
QUE_INCORRECT_COLOR: '#FF0000'
QUE_FILL_COLOR: '#000000'

FIX_CROSS_COLOR: '#ffffff'
FIX_CROSS_TIME_MS: 500


EXPERIMENT_BREAK_TIME_MS: 1000
#SESSION_BREAK_TIME_MS: 60000
SESSION_BREAK_TIME_MS: 5000
#TRAININGS_QUANTITY: 20
TRAININGS_QUANTITY: 2
#EXPERIMENTS_SESSIONS_QUANTITY: 3
EXPERIMENTS_SESSIONS_QUANTITY: 2
#EXPERIMENTS_QUANTITY: 30
EXPERIMENTS_QUANTITY: 3

 #od Bartka moze sie przyda
NO_TRAINING_TRIALS: [5, 1]
INTRA_BLOCK_TRAINIG: 2
NO_BLOCKS: 1
TRAINING_CSI: 10
STIM_LETTERS: ←→↑↓
STIM_SIZE: 25
STIM_SHIFT: 600
STIM_TIME: 15
REACTION_TIME: 90
MASK_TIME: 10
REACTION_KEYS_SEP: 30
CSI_BAND: [13, 18]